### PR TITLE
Add a deprecation notice onto search-cmd

### PR DESCRIPTION
**Pull request by coderoshi**
Yokozuna is the new hotness. Don't let people forget it with this classy deprecation notice.

basho/yokozuna#272

### CODE REVIEW

**Comment by jonmeredith** [comment]
Yokozuna vs Search2 'branding'.

**Comment by evanmcc** [comment]
Also the warning should be suppressable for people who're using search-cmd in scripts.

**Comment by jaredmorrow** [comment]
`echoerr` can be used from the env.sh https://github.com/basho/node_package/blob/develop/priv/base/env.sh#L50 so as to print on stderr and not affect runner scripts.

Also, placeholder to remember to format-patch / am to riak_ee after this is +1'd.

**Comment by coderoshi** [comment]
After painful deliberation, it looks like we're back to the "Riak Search" name.

**Comment by rzezeski** [comment]
+1, don't forget to update EE

**Comment by coderoshi** [comment]
@rzezeski https://github.com/basho/riak_ee/pull/220

**Pull request merged**
