### PR TITLE
Add man page docs for new search command

### PR DESCRIPTION
**Pull request by rzezeski**
Add man page docs for the new search command as well as its
sub-commands.

This is for PRs basho/yokozuna#350 and basho/yokozuna#349.

To view the man page run the following:

```
gzip -dc doc/man/man1/riak-admin.1.gz | nroff -man | less
```

### CODE REVIEW

**Comment by bookshelfdave** [comment]
if `man` sees a slash in the name, it will read in the .gz file:

```
man ./riak-admin.1.gz
```

see `man man` for more info

**Comment by seancribbs** [comment]
o man o man o man

**Comment by jrwest** [comment]
should the same be done for new security and bucket-type commands?

**Comment by rzezeski** [comment]
All commands should be updated/added but this PR is only for search.

**Comment by coderoshi** [comment]
+1 95bd660

I'm :thumbsup: on this as-is, but there are other undocumented commands. @jrwest mentioned a couple, but there are missing in total:
- aae-status
- bucket-type
- diag
- downgrade-objects
- reformat-indexes
- repair-2i
- security
- transfer-limit

**Comment by rzezeski** [comment]
Merged in ee in commit: `640fe7c2ddc48edca3471ea3e7bec4c096dcd052`

**Pull request merged**
