### PR TITLE
Added support for managing index repairs through riak-admin

### PR DESCRIPTION
**Pull request by cdahlqvist**
This PR depends on the following riak_kv PR: https://github.com/basho/riak_kv/pull/591

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Please remove the rebar.config file from the PR as it would change the rebar.config to point to a specific branch of riak_kv.

**Comment by cdahlqvist** [comment]
Rolled back my change to rebar.config to original 1.3.2 value.

**Comment by slfritchie** [comment]
Ping ... is this PR needed for Riak 2.0?  The prerequisite PR is still open and might be close without action because of other 2.0 features.  Thoughts?

**Comment by jaredmorrow** [comment]
2i Index repairs were added in https://github.com/basho/riak/pull/459, so I'm going to close this considering the riak_kv PR is also not merged.  We can resurrect if the riak_kv PR ends up being adjusted and put in.

**Comment by jrwest** [comment]
Just to clarify, the repair mentioned here is the existing repair mechanism [1] before the work done by @engelsanchez for 1.4.4+ and 2.0. Since we have a new mechanism and we never decided if indeed we wanted to expose the original method used here, I think closing is fine.

[1] http://docs.basho.com/riak/latest/ops/running/recovery/repairing-indexes/

**Comment by engelsanchez** [comment]
Wow, I got all sorts of confused when I got this today. We really have mega-overload problems on the word index :)

**Comment by jaredmorrow** [comment]
Yes, sorry too many "index"s in the code

**Pull request closed without merging**
