### PR TITLE
make reltool create generated configs dir

### PR DESCRIPTION
**Pull request by argv0**
I needed this to make "make rel" work on head of the develop branch.

### CODE REVIEW

**Comment by russelldb** [comment]
I had the same problem and this fixes it for me +1

**Comment by jaredmorrow** [comment]
Yes, since this https://github.com/basho/cuttlefish/pull/38 hasn't merged yet, you will have that problem. /cc @joedevivo

**Comment by jaredmorrow** [comment]
Okay, I merged basho/cuttlefish#38, confirm that you no longer need this PR.  @argv0 and @russelldb

**Comment by russelldb** [comment]
Yes, I can confirm that is fine for make rel / make devrel, but I still get an error from riak_test

https://gist.github.com/russelldb/356d2735b52fffa1c2e7

**Comment by jaredmorrow** [comment]
Which test is that Russell?  I'll check it out today.  Dumb question, but
did you rebuild your devrel that you ran riak_test against?

**Comment by russelldb** [comment]
`./riak_test -c rtdev -b bitcask -t verify_counter_converge`

I re-made devrel and re-ran rtdev-current. Don't worry about it…I have a pretty messed up set of branches, going to start from scratch tomorrow.

**Comment by russelldb** [comment]
OK…
https://gist.github.com/russelldb/1781bde57b750e1659bd fixes it for me.

**Comment by jaredmorrow** [comment]
Closing now that this is fixed in basho/cuttlefish#38

**Pull request closed without merging**
