### PR TITLE
Forward ports of older open PRs to cuttlefish

### PR DESCRIPTION
**Pull request by joedevivo**
This applies the intent of the following PRs in a post-cuttlefish world:
- #338 
- #361 

Thanks.

### CODE REVIEW

**Comment by joedevivo** [comment]
Please close #338 and #361 when this is merged

**Comment by joedevivo** [comment]
#361 was not ready, need to roll back commit

**Comment by seancribbs** [comment]
:+1: on the lager changes only. Either manually merge/cherry-pick or open a new PR.

**Comment by seancribbs** [comment]
In order for the second commit to work, we need:
- basho/riak_core#381
- basho/riak_api#34
- basho/riak_test#375

The related basho/riak_kv#629 was already merged.

/cc @Vagabond

**Comment by seancribbs** [comment]
@joedevivo All of the webmachine related pull-requests are merged, and @Vagabond have run riak_tests against this. :+1: to merge

**Comment by joedevivo** [comment]
o man o man o man

**Pull request merged**
