### PR TITLE
Allow dynamic number of devrel nodes to be created

### PR DESCRIPTION
**Pull request by evanmcc**
Allow for any number of devrel / stagedevrel nodes to be created.
`make devrel DEVNODES=60` will create a 60 node devrel

Original PR basho/riak_ee#90.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Shouldn't the dev*_vars_config files be gone in this PR?  Also, SNMP is only a EE feature so make sure that port is left out to avoid confusion.

**Comment by evanmcc** [comment]
I think that those pushes take care of it.

**Comment by jaredmorrow** [comment]
+1, making note that you intended to bump up the node count by default from 4 to 6

I'm fine with either

**Comment by evanmcc** [comment]
Good catch, will revert.

**Pull request merged**
