### PR TITLE
Added yokozuna enable option to app.config

### PR DESCRIPTION
**Pull request by ksauzz**
I added yokozuna enabled option to app.config. thanks.

### CODE REVIEW

**Comment by jj1bdx** [comment]
@ksauzz <del>Yokozuna will NOT be enable WITHOUT this app.config modification, right?</del>
To enable yokozuna, you need to set `{enabled, true}`. Correct me if I'm wrong.

**Comment by jj1bdx** [comment]
@ksauzz So this modification adds the flag for enabling the yokozuna functionality, but the flag itself is set to `false`, to prevent yokozuna to be accidentally enabled. Correct me if I'm wrong.

**Comment by ksauzz** [comment]
@jj1bdx Yes. Changing the flag to `true` is required to run yokozuna. This modification is to just show riak user the existence of the option. Unfortunately, there is no method to know how to run yokozuna except reading source code now. So I thinks the option should be revealed on the configuration file like riak_control. Also we should update 'Getting Started' on README of yokozuna after the merging.

**Comment by jj1bdx** [comment]
@ksauzz: +1. This patch is also applicable to the branch `yz-merge-master` (with 1 fuzz). A brief test here on OSX 10.8.3 with R15B03-1, the `enabled` flag worked as intended when changing the settings between `true` and `false`.
(BTW comment on wording: reveal -> disclose)

@rzezeski - Could you take a look at this?

**Comment by rzezeski** [comment]
@ksauzz Yes, the enabled option should be in the Yokozuna README.  This last week has been a bit hectic for me getting ready for RICON.

@jj1bdx Don't worry about `yz-merge-master` for now.  Once 1.4 drops all these side branches will go away as proper PRs are made to merge Yokozuna into Riak/KV master.

**Comment by ksauzz** [comment]
Thanks. ok, I'll try to update that.

**Pull request merged**
