### PR TITLE
Add https port to gen_dev and rebar overlay

### PR DESCRIPTION
**Pull request by andrelaszlo**
Changing the https port manually for all my devs each rebuild was
getting annoying, so I added a new variable `https_port` to
dev_vars.config and changed gen_dev accordingly. For consistency, I
also added the variable to vars.config.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
We are in the middle of our 2.0 development / test cycle where our config is going to change dramatically from having an app.config to having a generated config based around a simple configuration file.  Because of this, we probably won't merge this PR.  

In addition, it will probably be best to use your branch as we have changed our development branch from 'master' to 'develop', so we aren't merging PR's into 'master' for now.  

I'll /cc @joedevivo (who is the primary person reworking config) to make sure he knows to look out for this in 2.0.

Thanks for the PR, sorry it is not going to work with timing for us at the moment.

**Comment by andrelaszlo** [comment]
@jaredmorrow No problem, just thought I should share :) I noticed that you changed the whole config system in 2.0 but I didn't know if you were still adding stuff to the 1.4 branch. Looking forward to see the final result!

**Comment by jaredmorrow** [comment]
We are possibly releasing another rev on 1.4, but sadly 2.0 is keeping me too busy to give this a good look at the moment.

**Comment by slfritchie** [comment]
Howdy.  I don't believe that this kind of feature will be added to the 1.4 branch, and as Jared said, the Cuttlefish-based configuration scheme for Riak 2.0 changes your problem.  (Hopefully in a good way!)

**Comment by andrelaszlo** [comment]
Cuttlefish looks really promising, looking forward to seeing it in action. Thank you both for having a look!

**Comment by jaredmorrow** [comment]
I don't think the presence of cuttlefish affects this issue at all.  An https port still needs to be set as far as I know.  Handing this off to @joedevivo so he can make a call.

**Comment by andrelaszlo** [comment]
:bell: ping :bell:

**Pull request closed without merging**
