### PR TITLE
Update riak-admin and riak man pages

### PR DESCRIPTION
**Pull request by coderoshi**
The riak-admin and riak man pages were horrible out of date. The options were to update them, or delete them. Clearly, the former was the chosen path.

To test, just run man against the gz files.

```
man ./doc/man/man1/riak-admin.1.gz
man ./doc/man/man1/riak.1.gz
```
#524 opened the door
- [x] Also merge into EE

### CODE REVIEW

**Comment by reiddraper** [comment]
@coderoshi I dig the 'Also merge into EE' reminder. We should start adopting that until we've rolled them into the same repo.

**Comment by kellymclaughlin** [comment]
In the section describing the `config` option on the riak page there is a misspelling, _configration_, at the end of the description of the `effective` sub-option.

**Comment by kellymclaughlin** [comment]
Also in the `config` section in the description of the `describe` sub-option: _descrption_

**Comment by kellymclaughlin** [comment]
On the `riak-admin` page under the security sub-commands section, the description of the `ciphers` option uses _ciphers_ as the plural and _cypher_ as the singular. Why not just cipher? Not a big deal, just noticed the difference and was curious.

**Comment by kellymclaughlin** [comment]
Do you think we should we add some sort of disclaimer to the backup and restore command descriptions saying "Do not use! These do not work! DANGER, DANGER!"?

**Comment by kellymclaughlin** [comment]
On the `riak` page the description of `attach` uses existed instead of exited: _...which can be existed more safely_

**Comment by kellymclaughlin** [comment]
:+1:

**Pull request merged**
