### PR TITLE
Riak debug additions

### PR DESCRIPTION
**Pull request by slfritchie**
- Add 'blockdev' ouput to the platform (Linux) that supports it
- Add cluster-info output to the Riak commands section

### CODE REVIEW

**Comment by slfritchie** [comment]
Comments @bsparrow435 or @joecaswell or @jmshoffs0812 or other CSEs?

**Comment by bsparrow435** [comment]
I'm a bit wary of cluster-info being run by default as it's pretty heavy handed.. but I have not seen it take down a node before so i'm fine with this change. :+1:

**Comment by kuenishi** [comment]
My understanding is, cluster-info is cluster-wide by default while existing riak-debug is per-node. So I think it'd be better by making it local like:

```
dump cluster-info riak-admin cluster-info $CI local
```

**Comment by bsparrow435** [comment]
Good point @kuenishi, I agree. Otherwise, collecting a `riak-debug` from each node in the cluster will generate a lot of unnecessary load.

**Comment by slfritchie** [comment]
I'm not involved in a lot of support work lately, but when I am, it's annoying to have to go back and ask for diagnostic info batch #2.  If riak debug is supposed to be the be-all, do-all, one-stop shop, then why two stops?

Kota's point, however, I'll concede.  We recently had a customer who ran riak debug on all nodes in the same cluster ... if that was done via Ansible or multi-session tmux, for example, then it could very well be all running simultaneously.  I'll add a local only flag to the cluster info invocation, then merge.  Thanks!

**Pull request merged**
