### PR TITLE
Add riaknostic integration

### PR DESCRIPTION
**Pull request by seancribbs**
Adds `riak-admin diag` command with minimal integration to the riaknostic escript.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Needs to be added to the help line for `riak-admin`

**Comment by jaredmorrow** [comment]
I can see some people having trouble parsing this:

```
root@build-osol-0906-64:~# riak-admin diag
Attempting to restart script through sudo -u riak
20:16:23.704 [error] CRASH REPORT Process <0.44.0> with 0 neighbours crashed with reason: {error,badarg}
20:16:23.704 [error] Supervisor net_sup had child net_kernel started with net_kernel:start_link(['riak_diag627@127.0.0.1',longnames]) at undefined exit with reason {'EXIT',nodistribution} in context start_error
escript: exception error: no match of right hand side value 
                 {error,
                     {shutdown,
                         {child,undefined,net_sup_dynamic,
                             {erl_distribution,start_link,
                                 [['riak_diag627@127.0.0.1',longnames]]},
                             permanent,1000,supervisor,
                             [erl_distribution]}}}
  in function  riaknostic_node:start_net/0
  in call from riaknostic_node:try_connect/0
  in call from riaknostic_check:check/1
  in call from riaknostic:'-run/1-fun-1-'/2
  in call from lists:foldl/3
  in call from riaknostic:run/1
```

When the simple error is that riak is not running.   Don't know if that is really needed for the first release, but difficult to read stack traces is one of the things that people complain about and this is supposed to take some of that difficulty out.

**Comment by jaredmorrow** [comment]
`riak-admin diag` with no arguments returned:

```

root@build-osol-0906-64:~# riak-admin diag
Attempting to restart script through sudo -u riak
escript: exception error: bad argument
  in function  list_to_float/1
     called as list_to_float("format:")
  in call from riaknostic_util:binary_to_float/1
  in call from riaknostic_check_memory_use:check/0
  in call from riaknostic_check:check/1
  in call from riaknostic:'-run/1-fun-1-'/2
  in call from lists:foldl/3
  in call from riaknostic:run/1
```

The riaknostic page claims you can run it without arguments.

**Comment by jaredmorrow** [comment]
`riak-admin diag memory_use` returned:

```

root@build-osol-0906-64:~# riak-admin diag memory_use
Attempting to restart script through sudo -u riak
escript: exception error: bad argument
  in function  list_to_float/1
     called as list_to_float("format:")
  in call from riaknostic_util:binary_to_float/1
  in call from riaknostic_check_memory_use:check/0
  in call from riaknostic_check:check/1
  in call from riaknostic:'-run/1-fun-1-'/2
  in call from lists:foldl/3
  in call from riaknostic:run/1
```

**Comment by jaredmorrow** [comment]
Since the above are issues with riaknostic, and not the integration of the diag command with riak and riak_ee, I'll continue to test the basic command on multiple platforms rather than trying more specific commands.

**Comment by jaredmorrow** [comment]
This a documentation issue (the riaknostic.basho.com page), but going to add it here to keep everything in one place.

64-bit fedora packages install the lib directory to "/usr/lib64/riak/lib"   

I know, I know, picky.

**Comment by seancribbs** [comment]
@jaredmorrow The memory_use crash has already been fixed on Solaris, but anecdotally it also has problems on Ubuntu.  I've opened an issue for the net_kernel/net_sup crash https://github.com/basho/riaknostic/issues/17.

**Comment by seancribbs** [comment]
@jaredmorrow Also opened documentation issue for the Fedora directory: https://github.com/basho/riaknostic/issues/18

**Comment by jaredmorrow** [comment]
With the additions of the github issues, and the riak-admin help text, I'm +1 to merge.   Just tested Ubuntu (my last remaining platform).

So +1 to merge.

**Pull request merged**
