### PR TITLE
Add warning/max object limits

### PR DESCRIPTION
**Pull request by engelsanchez**

### CODE REVIEW

**Comment by evanmcc** [comment]
I think that these sizes are OK, but fwiw mostly the problematic sibling counts were much lower than this when I was a CSE.  warning at 25 and stopping at 100 sounds more reasonable to me, but I might be over-conservative.

**Comment by engelsanchez** [comment]
The sizes were pulled out of a hat. I would feel more comfortable with anything recommended from CSE experience.

**Comment by evanmcc** [comment]
K. Drop them to 25/100 and :+1:, we can tune more with CSE input post-ricon.

**Comment by engelsanchez** [comment]
@evanmcc I've changed the limits based on your CSE experience recommendation and I've opened a PR to apply a copy of this to Riak EE here https://github.com/basho/riak_ee/pull/182

**Pull request merged**
