### PR TITLE
Add batch size param to 2i reformat cmd

### PR DESCRIPTION
**Pull request by engelsanchez**
The default is 100.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
Not a big deal, but the output 

```
➜  riak git:(eas-2i-reformat-batch-size) ./bin/riak-admin  reformat-indexes 2 200                           
index reformat started with options: [{concurrency,2}]
check console.log for status information
```

Shows an output message talking about the first param, but not the second.  More of a stylistic / consistency comment.

**Comment by jaredmorrow** [comment]
Also, you don't exit on getting the wrong parameters, it just prints the message and still runs the script.

```
➜  riak git:(eas-2i-reformat-batch-size) ./bin/riak-admin  reformat-indexes 2 200 blah blah blah            
Usage: riak-admin reformat-indexes
       riak-admin reformat-indexes --downgrade
       riak-admin reformat-indexes <concurrency> [--downgrade]
       riak-admin reformat-indexes <concurrency> <batch size> [--downgrade]
index reformat started with options: [{concurrency,2}]
check console.log for status information
```

**Comment by engelsanchez** [comment]
Got it. Fixes on their way

**Comment by jaredmorrow** [comment]
+1

**Comment by jaredmorrow** [comment]
Patched into basho/riak_ee as well.

**Comment by engelsanchez** [comment]
Oops, thanks for taking care of that!

**Pull request merged**
