### PR TITLE
Develop 2.9

### PR DESCRIPTION
**Pull request by martinsumner**
Update basho develop-2.9 for Public Release Candidate

(will need a rep repoint eventually so that dependencies are pulled from basho not martinsumner)

### CODE REVIEW

**Comment by martinsumner** [comment]
@martincox - top level repo change (again just a merge into develop-2.9 branch)

**Comment by martincox** [comment]
Just starting to browse through all of these PRs - a really minor point; do we need to store the images in here (looks like they amount to a few MB)?

Also, I know you've raised the other PRs for deps, but they are still pointing at your GH in this rebar.config.

**Comment by martincox** [comment]
Also, interested to see the impact from the soft vnode limits in relation to the issues that we described earlier in the week around net_kernel timeouts. I'll try and get some comparative tests run early next week to see if it alleviates that problem.

**Comment by martinsumner** [comment]
Yes, good point on the pointing.  I will re-point it all after the big drops are in.

With hindsight I should have started a separate repo for all the images and release stuff.  I can take them out now, but I think with git their footprint may never go away.  I'll have a look into what can be done.

**Comment by llelf** [comment]
@martinsumner update the version in reltool.config

**Comment by martinsumner** [comment]
@martincox I've removed all the images from the PR now.  I have a separate repo for the testing notes now.

**Comment by martinsumner** [comment]
rebar.config updated now.

PR depends on associated develop-2.9 PRs to:

[riak_kv](https://github.com/basho/riak_kv/pull/1675)
[riak_core](https://github.com/basho/riak_core/pull/924)
[riak_repl](https://github.com/basho/riak_repl/pull/789)

**Comment by martinsumner** [comment]
@martincox will go ahead with merge into develop-2.9 this evening, unless I hear otherwise.  Hope that's OK.  Ta

**Pull request merged**
