### PR TITLE
Add riak-admin search subcommand

### PR DESCRIPTION
**Pull request by rzezeski**
Add a search subcommand to riak-admin for administrating
Yokozuna.

This is related to basho/yokozuna#349.

### CODE REVIEW

**Comment by jaredmorrow** [comment]
+1, works for me when I used the yz and kv PR's.

Please patch riak_ee with the same change.

**Comment by rzezeski** [comment]
@jaredmorrow is that a +1 for all three?

**Comment by jaredmorrow** [comment]
My intention was a +1 for just this PR.  It printed correctly, so if no one else gives you a kv +1 soon, I'll check that code tomorrow and upgrade my +1 to be all-inclusive.

**Comment by rzezeski** [comment]
Okay. FWIW KV is simply an export of 3 functions and Yokozuna is a copy/paste of what KV AAE does.

**Pull request merged**
