### PR TITLE
Add ciphers command

### PR DESCRIPTION
**Pull request by Vagabond**
Add a command for viewing/setting the ciphersuite used.

### CODE REVIEW

**Comment by Vagabond** [comment]
See also basho/riak_core#469

**Comment by bookshelfdave** [comment]
+1

**Comment by jaredmorrow** [comment]
Feel free to push to EE

**Comment by slfritchie** [comment]
Ping ... the prereq (?) issue, basho/riak_core#469, has been merged.  Also, Jared's comment about EE also applies.  I'm working on the 25th, so if y'all don't mind, I can do both repos tomorrow.

**Pull request merged**
