### PR TITLE
bucket type riak-admin commands

### PR DESCRIPTION
**Pull request by jrwest**
this PR relies on https://github.com/basho/riak_core/pull/402, https://github.com/basho/riak_kv/pull/673, and https://github.com/basho/riak_kv/pull/677
- [ ] apply patch to riak_ee

Examples:

```
$ riak-admin bucket-type status atype
atype is not an existing bucket type

$ riak-admin bucket-type create atype '{"props": {"n_val": 5, "allow_mult": true}}'
atype created

$ riak-admin bucket-type status atype
atype has been created and may be activated

<<"n_val">>: 5
<<"allow_mult">>: true
precommit: []
postcommit: []
n_val: 3
last_write_wins: false
chash_keyfun: {riak_core_util,chash_std_keyfun}
allow_mult: false
active: false
claimant: 'dev1@127.0.0.1'

$ riak-admin bucket-type activate atype
atype has been activated

$ riak-admin bucket-type status atype
atype is active
....

$ riak-admin bucket-type list
test (active)
reallylongbuckettypenamethatmaycauseproblemsfordisplay (not active)
atype (active)

$ riak-admin bucket-type update atype '{"props": {"n_val": 9}}'
atype updated

$ riak-admin bucket-type reset atype
atype reset
```

### CODE REVIEW

**Comment by Vagabond** [comment]
The json on the command line makes me not too happy, seems very error prone.

**Comment by jrwest** [comment]
@Vagabond i thought the json was what we discussed? I agree its not ideal and am open to alternatives but this was the quickest way

**Comment by Vagabond** [comment]
I don't have a good alternative. I guess we can try JSON for now, the hard part is the issue of datatypes, so a simple key=value syntax won't work, without specifiying the datatype of each possible bucket prop. +1 as the best we can do for now.

**Comment by jaredmorrow** [comment]
I rebased against `develop` to make this merge-able.  Sorry for the ugly commit.

+1 from me

**Comment by Vagabond** [comment]
I think you fucked up the rebase, bro.

**Comment by jaredmorrow** [comment]
Yeah, I really did.  Jordan is going to just format-patch it in.  I did everything by the rebase book and obviously screwed up.

**Comment by Vagabond** [comment]
I'm +1 on this.

**Comment by jrwest** [comment]
merged manually in https://github.com/basho/riak/commit/b80235e891f0eb695848b436ff1e8df4f0f00ede

**Pull request closed without merging**
