### PR TITLE
riak escript

### PR DESCRIPTION
**Pull request by ghost**
This allows a user to run an escript without having to figure out
where their version of bundled Erlang for Riak is located.

This is extremely useful when we write Erlang scripts to expose
functionality that has not been implemented yet elsewhere, such as
examining message queues.

### CODE REVIEW

**Comment by bsparrow435** [comment]
Tested on Ubuntu and OSX. +1 to merge.

**Comment by dizzyd** [comment]
Hm...is that going to do the right thing when you pass other arguments to the escript? I.e. 

riak escript myescript.erl arg1 arg2

**Comment by ghost** [comment]
That's why I call shift to globber the first argument, and pass in $@ for the rest of the arguments.

```
./bin/riak escript ~/src/basho/basho-escripts/bitcask_dump_keys.escript \
data/bitcask/1118962191081472546749696200048404186924073353216 \
/tmp/

Opening bitcask: "data/bitcask/1118962191081472546749696200048404186924073353216"
Opening output file: "/tmp/1118962191081472546749696200048404186924073353216.keys"

cat /tmp/1118962191081472546749696200048404186924073353216.keys 
__riak_client_test__,key1
```

**Comment by dizzyd** [comment]
Got it, thanks. +1 to merge, but we also need to add this to the EDS version of script.

**Pull request merged**
