### PR TITLE
add 'riak-admin aae-status' to riak-debug.

### PR DESCRIPTION
**Pull request by ksauzz**
Backports the fix from 2.0.

### CODE REVIEW

**Comment by bookshelfdave** [comment]
+1, commands/riak_aae_status appears in the generated .tgz when riak-debug is run with this branch

**Comment by cmeiklejohn** [comment]
Merging to meet the pre13 deadline.

**Comment by cmeiklejohn** [comment]
@metadave Do we need to also apply this back-ported fix to riak_ee as well?

**Comment by bookshelfdave** [comment]
yeah, https://github.com/basho/riak_ee/pull/219

**Pull request merged**
