### PR TITLE
Add new rebar binary and erlydtl opts info toplevel rebar.config for solving dialyzer glitches

### PR DESCRIPTION
**Pull request by jj1bdx**
Applying the pull request will solve the dialyzer glitches caused by ErlyDTL templates and Protobuff `.proto` files, shown as the errors below:

```
dialyzer: Could not get abstract code for file:   /home/kenji/src/riak/deps/riak_control/ebin/index_dtl.beam (please recompile it with   +debug_info)

dialyzer: Could not get abstract code for file: /home/kenji/src/riak/deps/riak_core/ebin/riak_core_pb.beam (please recompile it with +debug_info)
```

### CODE REVIEW

**Comment by jaredmorrow** [comment]
+1

Two notes, this now sets the minimum build erlang to 14b04 from 14b03, but that's reasonable.  Also, with PR's from now on, can you branch from the basho organization @jj1bdx rather than your personal account.  It makes it a little easier for us to all collaborate on PR's.

Tested compile on osx, linux, solaris.

**Comment by jj1bdx** [comment]
Will do on branching from The basho organization with my @jj1bdx access rights.

I've tested locally on FreeBSD 9.1R amd64 and Ubuntu 12.10 x86_64.

**Comment by jaredmorrow** [comment]
Feel free to merge

**Comment by jj1bdx** [comment]
Note: I removed the original fork at jj1bdx/riak because all necessary commits are copied here.

**Pull request merged**
