### PR TITLE
use exometer metrics

### PR DESCRIPTION
**Pull request by uwiger**
This is a new pull request for the Exometer adaptation, with a cleaner commit history (all changes collected into one diff).

Depends on corresponding PRs in riak_core, riak_kv, riak_api, riak_pipe, riak_search, yokozuna.

Highlights of the exometer adaptation:
- Slightly better performance
- Simplified code in riak: less specific knowledge of metric types scattered around in the core, and less need for caching of metrics, since metrics sampling is cheaper.
- Integrated stats reporting support (e.g. via collectd) in exometer
- More flexible function metrics
- Exometer support for custom probes and metrics
- Better metrics query support
- SNMP reporting built into exometer
- Support for disabling existing metrics for further reduced overhead.
- Stat names now have a 'system prefix' (default: 'riak'), to simplify separation of metrics reported from co-located riak_core-based applications. The prefix is turned into a compile-time constant.

### CODE REVIEW

**Comment by uwiger** [comment]
Note, the old PR was #448

**Comment by jburwell** [comment]
The verify_riak_stats test fails against this branch with the following error:

```
17:02:50.542 [info] verify_riak_stats prereqs: []
17:02:50.542 [notice] Running Test verify_riak_stats
17:02:51.545 [info] Test Runner `uname -a` : Darwin jburwell-basho.local 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64

17:02:51.545 [info] Riak path: "/Users/jburwell/rt/riak-exometer-2.0"
17:02:51.579 [info] Running: /Users/jburwell/rt/riak-exometer-2.0/dev/dev1/bin/riak start
17:02:54.478 [info] Wait until 'dev1@127.0.0.1' is pingable
17:02:54.745 [info] Wait until 'dev1@127.0.0.1' is pingable
17:02:54.745 [info] Wait until riak_core_ring_manager is up on 'dev1@127.0.0.1'
17:02:54.746 [info] Check 'dev1@127.0.0.1' is a singleton
17:02:54.825 [info] Deployed nodes: ['dev1@127.0.0.1']
17:02:54.825 [info] Waiting for services [riak_kv] to start on ['dev1@127.0.0.1'].
17:03:04.838 [info] Wait until nodes are ready : ['dev1@127.0.0.1']
17:03:14.976 [error] Error in process <0.127.0> on node 'riak_test@127.0.0.1' with exit value: {{assertNotEqual_failed,[{module,verify_riak_stats},{line,122},{expression,"0"},{value,0}]},[{verify_riak_stats,'-verify_nz/2-fun-0-',1,[{file,"tests/verify_riak_stats.erl"},{line,122}]},{verify_riak_stats,'-verify_nz/2-lc$^0/1-0-'...


17:03:14.976 [warning] verify_riak_stats failed: {{assertNotEqual_failed,[{module,verify_riak_stats},{line,122},{expression,"0"},{value,0}]},[{verify_riak_stats,'-verify_nz/2-fun-0-',1,[{file,"tests/verify_riak_stats.erl"},{line,122}]},{verify_riak_stats,'-verify_nz/2-lc$^0/1-0-',2,[{file,"tests/verify_riak_stats.erl"},{line,122}]},{verify_riak_stats,'-verify_nz/2-lc$^0/1-0-',2,[{file,"tests/verify_riak_stats.erl"},{line,122}]},{verify_riak_stats,confirm,0,[{file,"tests/verify_riak_stats.erl"},{line,32}]},{riak_test_runner,return_to_exit,3,[{file,"src/riak_test_runner.erl"},{line,159}]}]}
17:03:14.976 [error]
================ verify_riak_stats failure stack trace =====================
{{assertNotEqual_failed,[{module,verify_riak_stats},
                         {line,122},
                         {expression,"0"},
                         {value,0}]},
 [{verify_riak_stats,'-verify_nz/2-fun-0-',1,
                     [{file,"tests/verify_riak_stats.erl"},{line,122}]},
  {verify_riak_stats,'-verify_nz/2-lc$^0/1-0-',2,
                     [{file,"tests/verify_riak_stats.erl"},{line,122}]},
  {verify_riak_stats,'-verify_nz/2-lc$^0/1-0-',2,
                     [{file,"tests/verify_riak_stats.erl"},{line,122}]},
  {verify_riak_stats,confirm,0,
                     [{file,"tests/verify_riak_stats.erl"},{line,32}]},
  {riak_test_runner,return_to_exit,3,
                    [{file,"src/riak_test_runner.erl"},{line,159}]}]}
============================================================================

17:03:14.976 [notice] verify_riak_stats Test Run Complete
17:03:14.979 [info] Stopping cover

Test Results:
verify_riak_stats-bitcask: fail
---------------------------------------------
1 Tests Failed
0 Tests Passed
That's 0.0% for those keeping score
```

Additionally, the following log entries are occurring repeatedly during the test run:

```
2014-07-31 17:17:23.712 [warning] <0.156.0>@exometer_report_collectd:exometer_info:194 Could not reconnect: {error,enoent}
2014-07-31 17:17:53.713 [info] <0.156.0>@exometer_report:reporter_loop:1062 Custom invocation: exometer_report_collectd({exometer_callback,reconnect})
2014-07-31 17:17:53.713 [info] <0.156.0>@exometer_report_collectd:exometer_info:189 Reconnecting: {st,auto,"/var/run/collectd-unixsock",exometer,auto,10000,
[{[riak,riak_kv,node,puts,one],"counter"}],5000,5000,30000,undefined}
```

It seems to me that the collectd reporter should be disabled by default because this yields a tremendous amount of log spam.

**Comment by uwiger** [comment]
Seems to be the ring_creation_size metric that's missing (although the test output doesn't say). I'll look into it.

I was thinking about setting the reporter to off by default, and providing a cuttlefish toggle. Another possibility would be to limit the number of retries if it can't find the collectd socket. It makes little sense to retry endlessly.

**Comment by jburwell** [comment]
Working with @russelldb, I have put together a [performance test plan](https://gist.github.com/jburwell/4921f80fc86d6d31f386) to verify that Exometer's measurement overhead is less than or equal to Folsom's overhead.

**Comment by jburwell** [comment]
Performed functional testing with the Bitcask, LevelDB, and memory backends to verify the completeness of the metrics reports.

For all three (3) backends, the following stats were reported by Folsom in Riak 2.0.0RC1 but not by Exometer branch:
- consistent_get_objsize_100
- consistent_get_objsize_95
- consistent_get_objsize_99
- consistent_get_objsize_mean
- consistent_get_objsize_median
- consistent_get_time_100
- consistent_get_time_95
- consistent_get_time_99
- consistent_get_time_mean
- consistent_get_time_median
- consistent_gets
- consistent_gets_total
- consistent_put_objsize_100
- consistent_put_objsize_95
- consistent_put_objsize_99
- consistent_put_objsize_mean
- consistent_put_objsize_median
- consistent_put_time_100
- consistent_put_time_95
- consistent_put_time_99
- consistent_put_time_mean
- consistent_put_time_median
- consistent_puts
- consistent_puts_total
- leveldb_read_block_error
- read_repairs_primary_notfound_count
- read_repairs_primary_notfound_one
- read_repairs_primary_outofdate_count
- read_repairs_primary_outofdate_one
- riak_core_stat_ts
- riak_kv_stat_ts
- riak_pipe_stat_ts

/cc @uwiger

**Comment by russelldb** [comment]
The stat_ts stats are timestamps the say when the cached stat was calculated. 

-------- Original message --------

**Comment by jburwell** [comment]
@russelldb as I understand Exometer, it can be configured to cache.  @uwiger, if my understanding is correct, would it be correct to update these values when caching is enabled and report "0" when it is disabled?  

/cc @jonmeredith

**Comment by jonmeredith** [comment]
I'd be tempted to keep it as time based and keep the current so that if we
just have the body of HTTP/JSON requests we'll be able to work out when
readings were from.

If we already have it in a different field, I'm fine with zero.
Not sure if there's any value in a 'cached: true/false' type field.

Jon

On Tue, Aug 12, 2014 at 11:26 AM, John Burwell notifications@github.com
wrote:

> @russelldb https://github.com/russelldb as I understand Exometer, it
> can be configured to cache. @uwiger https://github.com/uwiger, if my
> understanding is correct, would it be correct to update these values when
> caching is enabled and report "0" when it is disabled?
> 
> /cc @jonmeredith https://github.com/jonmeredith
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/basho/riak/pull/576#issuecomment-51947211.

## 

Jon Meredith
VP, Engineering
Basho Technologies, Inc.
jmeredith@basho.com

**Comment by uwiger** [comment]
I can certainly put them back in, and have them report 0 unless I can find some other sensible interpretation for them.

Caching in exometer would, in any event, not be exactly like the riak_core_stat_cache, which cached _everything_. Exometer would only cache the metrics that cost a lot to sample. One metric type that fits that description is the CPU stats, but it actually handles it internally. One day, perhaps I'll rewrite it to use the exometer cache (eat one's own dog food ...), but it doesn't seem a high priority atm.

**Comment by jburwell** [comment]
@jonmeredith My suggestion was in the spirit of maintaining compatibility with 2.0.0 stats output.  However, based on @uwiger's comments, it seems as though these metrics is obsolete in the context of the Exometer integration. 

@jonmeredith To confirm, it is acceptable for Exometer to drop the riak_core_stat_ts, riak_kv_stat_ts, and riak_pipe_stat_ts stats.

**Comment by jburwell** [comment]
The following are the tasks required to complete the review of the PR:
- **Coverage Testing**: Compare the output of stats between these branches and Riak 2.0 RC1 to ensure all stats are present.
  - [ ] bitcask Backend
  - [ ] leveldb Backend
  - [ ] memory Backend
  - [ ] Strong Consistency Enabled
  - [ ] Yokozuna Enabled
  - [ ] Legacy Search Enabled
  - [ ] Using map datatype
  - [ ] Using set datatype
  - [ ] Using counter datatype
  - [ ] Using register datatype
  - [ ] MDC Enabled
- **Comparison Tests**: All metrics values are within +/- 5% with the exception of version strings (which should be equal) and handoffs related metrics
  - [ ] bitcask Backend
  - [ ] leveldb Backend
  - [ ] memory Backend
  - [ ] Strong Consistency Enabled
  - [ ] Yokozuna Enabled
  - [ ] Legacy Search Enabled
  - [ ] Using map datatype
  - [ ] Using set datatype
  - [ ] Using counter datatype
  - [ ] Using register datatype
  - [ ] MDC Enabled
- \- [ ] **Overhead Verification**: The impact of Exometer and Folsom on throughput, get, and update latencies should be within +/- 5% for 1, 2, 5, 10, and 50 stats clients
- **riak-admin stats functionality**: Add r_t test cases to verify the operation of the following riak-admin stats commands added for this enhancement:
  - [ ] Implement show command test case 
  - [ ] Pass show command test case
  - [ ] Implement show-all command test case
  - [ ] Pass show-all command test case
  - [ ] Implement enable command test case
  - [ ] Pass enable command test case 
  - [ ] Implement disable command test case
  - [ ] Pass disable command test case
  - [ ] Implement reset command test case
  - [ ] Pass reset command test case
  - [ ] Implement info command test case
  - [ ] Pass info command test case
- [ ] Pass the verify_stats test
- [ ] Pass the replication_stats test
- [ ] Implement/pass handoff stats tests
- [ ] CSE/Product Management review of the stats cuttlefish schema

**Comment by jburwell** [comment]
The latest coverage tests found the following keys present in the Folsom-based stats, but not Exometer for the bitcask, leveldb, and memory backends:
- consistent_get_objsize_100
- consistent_get_time_100

The Exometer stas contained the following stats that were not present in the Folsom stats:
- afunix_version
- bear_version
- consistent_get_objsize_max
- consistent_get_time_max
- exometer_version
- list_fsm_create_error_total
- list_fsm_create_total
- list_fsm_error

Comparison of the stats values are capturing this Google Docs spreadsheet (https://docs.google.com/a/basho.com/spreadsheets/d/1lqTnmmDwZ6uOdtO8raI9TDcJ77M8IxyRSysTF7wWPdU/edit#gid=1013106721). 

/cc @uwiger

**Comment by jburwell** [comment]
Executed another round of coverage tests on 24 Sept 2014 for bitcask, leveldb, memory, and Yokozuna search.  For bitcask, leveldb, and memory, delete operations were added to run to trigger a wider range of metrics.  I have encountered a error with Basho Bench's mapreduce operation that I will resolve for the next round of testing.  For this run, the following metrics were present in the Folsom stats but not Exometer:
- consistent_get_objsize_100
- consistent_get_time_100
- search_index_fail_count
- search_index_fail_one
- search_index_latency_95
- search_index_latency_99
- search_index_latency_999
- search_index_latency_max
- search_index_latency_median
- search_index_latency_min
- search_index_throughput_count
- search_index_throughtput_one
- search_query_fail_count
- search_query_fail_one
- search_query_latency_95
- search_query_latency_99
- search_query_latency_999
- search_query_latency_max
- search_query_latency_median
- search_query_latency_min
- search_query_throughput_count
- search_query_throughput_one

The following metrics were present in the Exometer stats but not Folsom:
- afunix_version
- bear_version
- consistent_get_objsize_max
- consistent_get_time_max
- exometer_version
- list_fsm_create_error_total
- list_fsm_create_total
- list_fsm_error
- read_repairs_primary_outofdate_count
- read_repairs_primary_outofdate_one

A comparison of the stats values are captured this [spreadsheet](https://docs.google.com/a/basho.com/spreadsheets/d/1Xd6MLQDSZyM12-oc1kMh99x57OUf5Jd3OG9VTbq8sPg/edit#gid=1965578191).

**N.B.** The search stats appear inconsistent.  The Basho Bench job issues a series of queries that should fail (i.e. querying for an integer value out of range).  However, the stats run reflects no query failures.  Also, the search_index_latency and search_index_throughput_one histograms have a zero value yet the other histograms reflect search operation activity.  Therefore, a zero values for these metrics seem inconsistent.  I will investigate these results before the next test run to ensure that my assumption/expectations are correct, the Basho Bench job is defined properly, and/or YZ metrics collection is correct.

/cc @uwiger @jonmeredith @coderoshi

**Comment by jburwell** [comment]
Executed a third round of coverage/comparison tests on 2 October 2014.  For this run, the following metrics were present in the Folsom stats but not Exometer:
- search_index_fail_count
- search_index_fail_one
- search_query_fail_count

The following metrics were present in the Exometer stats but not Folsom:
- afunix_version
- bear_version
- exometer_version
- list_fsm_create_error_total
- list_fsm_create_total
- list_fsm_error
- read_repairs_primary_outofdate_count
- read_repairs_primary_outofdate_one
- search_index_latency_95
- search_index_latency_99
- search_index_latency_999
- search_index_latency_max
- search_index_latency_median
- search_index_latency_min
- search_index_throughput_count
- search_index_throughtput_one
- search_query_fail_one
- search_query_latency_95
- search_query_latency_99
- search_query_latency_999
- search_query_latency_max
- search_query_latency_median
- search_query_latency_min
- search_query_throughput_count
- search_query_throughput_one
- search_search_query_fail_count

A comparison of the stats values are captured this [spreadsheet](https://docs.google.com/a/basho.com/spreadsheets/d/1ESLqcyXyTSKasrZAfMMxCZCEdhRBadJhi1g1Yi1cE9I/edit?pli=1#gid=1965578191).

/cc @uwiger @jonmeredith

**Comment by jburwell** [comment]
Re-executed the coverage/comparison test suite to test @uwiger's latest changes.  The following metrics were present in Riak 2.0.0, but not the feuerlabs-exometer2 branch:
- converge_delay_last
- converge_delay_max
- converge_delay_min
- search_index_fail_count
- search_index_fail_one
- search_query_fail_count
- read_repairs_primary_notfound_count
- read_repairs_primary_notfound_one

The following metrics were present in the feuerlabs-exometer2 branch, but not Folsom:
- afunix_version
- bear_version
- exometer_version
- list_fsm_create_error_total
- list_fsm_create_total
- list_fsm_error
- late_put_fsm_coordinator_ack
- node_get_fsm_in_rate
- node_get_fsm_out_rate
- node_put_fsm_active
- node_put_fsm_in_rate
- node_put_fsm_out_rate
- rings_reconciled
- search_index_latency_95
- search_index_latency_99
- search_index_latency_999
- search_index_latency_max
- search_index_latency_median
- search_index_latency_min
- search_index_throughput_count
- search_index_throughtput_one
- search_query_fail_one
- search_query_latency_95
- search_query_latency_99
- search_query_latency_999
- search_query_latency_max
- search_query_latency_median
- search_query_latency_min
- search_query_throughput_count
- search_query_throughput_one
- search_search_query_fail_count
- read_repairs_primary_outofdate_count
- read_repairs_primary_outofdate_one

A comparison of the stats values are captured in this [spreadsheet](https://docs.google.com/a/basho.com/spreadsheets/d/1YC1GbTEmaSaiQAScTIICqjk1_JojESNiv0gELdbomK4/edit#gid=1965578191).

/cc @uwiger @jonmeredith

**Comment by krestenkrab** [comment]
@uwiger, where can I find an example of how to simply dump all stats to a graphite?

**Comment by jburwell** [comment]
@krestenkrab The best way is to use collectd to pull off the HTTP endpoint and push over to Graphite.  See this [gist](https://gist.github.com/jburwell/b58b2a794bbdc1ac5e08) for a set of collectd configuration templates that will pull both Riak stats and the relevant system stats.  The collectd.conf.template should be rendered into /etc/collectd and the other templates into etc/collect.d. 

**N.B.** The Riak stats being pulled in the gist are a subset of the available stats.   Therefore, you may need to change the list to match your needs.

**Comment by jburwell** [comment]
Superseded by https://github.com/basho/riak/pull/621

**Comment by krestenkrab** [comment]
@jburwell thanks! /cc @rsltrifork @lixen

**Pull request closed without merging**
