### PR TITLE
Add known issue for LWW Registers in Riak Maps

### PR DESCRIPTION
**Pull request by lenary**
basho/riak_dt#100 - mentioned in the mumble today

### CODE REVIEW

**Comment by seancribbs** [comment]
:+1:

**Comment by russelldb** [comment]
Disagree -1

**Comment by russelldb** [comment]
If the LWW Reg was a key in Riak, does "time go backwards" if you write K={a, 2}, delete K, K={b, 0} ?

**Comment by seancribbs** [comment]
@russelldb I think there's a subtle difference between "wrong" and "surprising", but from the user's perspective both could be "wrong". Let's discuss more in detail Monday as a group.

**Comment by russelldb** [comment]
ok, thanks.

**Comment by seancribbs** [comment]
Closing. To summarize:

The proper semantics don't really exist, we are figuring them out. Once we have determined them, the change can be made. Making this a Known Issue implies we know or at least have vague idea of what needs fixing. The reset-remove semantic can indeed cause things to "go back in time", but we know that LWW is lossy. _Caveat implementor!_

**Pull request closed without merging**
