### PR TITLE
Added handling of parameter -n to `riak-admin top` in order to allow user to specify number of iterations to run.

### PR DESCRIPTION
**Pull request by cdahlqvist**

### CODE REVIEW

**Comment by jaredmorrow** [comment]
This branch looks like it was branched from 'master', but then is trying to merge into 'develop'.  Can you fix and resubmit?  /cc'ing @slfritchie will be good since he was the original author.

**Comment by jaredmorrow** [comment]
Actually it might have been based off of 1.4, because it is trying to pull in tagged rebar.config settings as well.

**Comment by slfritchie** [comment]
Ping ... is this PR needed for Riak 2.0?  Looks like it's lacking rebasing & final review?

**Comment by jaredmorrow** [comment]
@slfritchie I don't use top a lot, so I wouldn't know how useful this would be for people.  It probably won't make 2.0 considering it needs a rebase and review.

**Comment by jaredmorrow** [comment]
Closing due to lack of activity / response.

**Pull request closed without merging**
